// ✅ Only ONE site should be uncommented at a time

export const websites = [
    // { baseUrl: 'https://ap-radiance.agentimage.com/', site: 'Radiance', pass: 'lBfZVC5TK^xPEyi&0f' }, 
    { baseUrl: 'https://ap-purist.agentimage.com/', site: 'Purist', pass: '(kK15NX6pl$)xLiL6%' },
    // { baseUrl: 'https://ap-endeavor.agentimage.com/', site: 'Endeavor', pass: 'GiJV*cEsmfZJb@5Mqu'},
    // { baseUrl: 'https://ap-galaxy.agentimage.com/', site: 'Galaxy', pass: 'oAVixqyAuJC#&n%P$v'},
    // { baseUrl: 'https://ap-panorama.agentimage.com/', site: 'Panorama', pass: 'sOR@koqEAb2dI9t6EodOsv1^'},
    // { baseUrl: 'https://ap-beacon.agentimage.com/', site: 'Beacon', pass: 'stsFy)Jw$o8geWVIkT'},
    // { baseUrl: 'https://ap-legacy.agentimage.com/', site: 'Legacy', pass: '4Kc@bqJpd7EzvLSFWt8KT?AaxH'},
    // { baseUrl: 'https://premierrealestategrp.com/', site: 'Premiere Real Estate GRP', pass: 'VCCLr4vqNNPyKxDdDIAvqiNMH'},
    // { baseUrl: 'https://domcava.com/', site: 'Domcava', pass: '4Kc@bqJpd7EzvLSFWt8KT?AaxH'},
    // { baseUrl: 'https://staging-ap-equinox.agentimage.com/', site: 'Equinox', pass: '6b!zWhjFICoRnIJXnS'}, 
    // { baseUrl: 'https://staging-ap-ascend.agentimage.com/', site: 'Ascend', pass: 'yIf4cE2AeInyJTpwjss)x8UB'},
    // { baseUrl: 'https://staging-ap-elevate.agentimage.com/', site: 'Elevate', pass: 's^(!5Qt!QO#TXeOiN7BJWZD4'},
    // { baseUrl: 'https://pearllinresidences.com/', site: 'Pearl Lin', pass: 'pUMSYx75gPXxuDhZ6PRN'}, 
    // { baseUrl: 'https://www.adamkrz-dreamhouse.com/', site: 'Adam KRZ', pass: 'vEj5g16zAVSfyKtDa0oA'}, 
    // { baseUrl: 'https://www.homesbyzach.com/', site: 'Homes by Zach ', pass: 'aht1NxR5VvGhlSLjcvtk'}, 
    // { baseUrl: 'https://ap-theoryresidentialgroupcom.uat.aios-staging.com/', site: 'Theory Residential Group', pass: 'aht1NxR5VvGhlSLjcvtk'},
    // { baseUrl: 'https://www.andersonauction.com/', site: 'Anderson', pass: 'l8t5ERFA2EqlLnQ26nmj'}, 
    // { baseUrl: 'https://m-andrade-realty.com/', site: 'Andrade', pass: 'JU0Wmc3RKtUzcxfOAwfbDc3gc'}, 
    // { baseUrl: 'https://teamswanbeck.com/', site: 'Team Swanbeck', pass: 'eZRHx40ekLi1iNqfltXvXgWct'}, 
    // { baseUrl: 'https://gracechicca.com/', site: 'Grace Cicca', pass: 'o4eJyFsiSKadOSOk7ho3'},
    // { baseUrl: 'https://www.brettharrishomes.com/', site: 'Bret Harris', pass: '3&XjuEhRdeJ%Am@miIGGDXQ@Ly'},
    // { baseUrl: 'https://www.buildwithbcpc.com/', site: 'Build with BCPC', pass: 'WDYbwpDkJyVqv0ObEV943nRI5'},
    // { baseUrl: 'https://www.iconic.realestate/', site: 'Iconic Real Estate', pass: 'ItFPvUC0xwRJR8zS11h4'},
    // { baseUrl: 'bbremmer-pendingcom.rs6.aios-staging.com/', site: 'BBremmer', pass: '8koYU1coejMx7jINtBQOnAlXi'},
    // { baseUrl: 'https://www.barrylevinsonadvisory.com/', site: 'Barry Levinson', pass: 'TEIjYs0PLsyPmZBEPyEbtIA7P'},
    // { baseUrl: 'calltheconleyscom.ap.aios-staging.com/', site: 'Call the Conleys', pass: 'i8Y0zjZyJoa4T91omS3k'},
    // { baseUrl: 'https://signatureshorthills.com/', site: 'Signature Hills', pass: 'pUatTiFZcjfFtcZSRGlL5ViDC'},
    // { baseUrl: 'https://devosre.com/', site: 'Devos', pass: 'NsfuhqldcD6PndtUcSr5mrwB9'},
    // { baseUrl: 'https://www.usswluxury.net/', site: 'USS Luxury', pass: 'ZumwZDUFcVUo4dxKwwhmWPyEN'},
    // { baseUrl: 'https://www.cny.realestate/', site: 'CNY', pass: 'FVwCj6JJIsHs8HhcMWYf'},
    // { baseUrl: 'https://www.propertiesofmaui.com/', site: 'Properties of Maui', pass: 'a4YEBYBTNOWWkm4uNmOd'},
    // { baseUrl: 'https://www.rockcityre.com/', site: 'Rock City RE', pass: 'mmNYkHI3szWjpeMbA3ifQwLP7'},
    // { baseUrl: 'https://www.theracheteam.com/', site: 'Rache Boston', pass: 'wfTCVJ0oWWH1iHgYXo1C'},
    // { baseUrl: 'https://soldsistersgroup.com/', site: 'Sold Sisters', pass: 'zpEChmKMCLqCBytN'},
    // { baseUrl: 'https://czrealty.com/', site: 'CZ Realty', pass: 'C51@7Rwxc}h>Mr[N'},
    // { baseUrl: 'http://bpellegrino-pendingcom.rs6.aios-staging.com/', site: 'The Agency Cleveland', pass: 'MfpBzgCcFj1ODWQCrp0AtwEb8'},
    // { baseUrl: 'https://www.zaran.com/', site: "Zaran", pass: 'FkaoS7FOmMfq5VMLDOqG'},
    // { baseUrl: 'https://www.nelispurrellrealtor.com/', site: "Neli Spurell Realtor", pass: 'H5xTruusnCJieBYaAb8f'},
    // { baseUrl: 'https://marcangelogroup.com/', site: "Marc Angelo Group", pass: '}FWS8]gPsibLweg]'}
    // { baseUrl: 'https://brockbremmer.com/', site: "Brock Bremmer", pass: '8koYU1coejMx7jINtBQOnAlXi'},
    // { baseUrl: 'https://charlesdesertrealestate.com/', site: "Charles Desert Real Estate", pass: 'WJUf9kryR9NqC3oRynPUPaCJx'},
    // { baseUrl: 'https://mindsetmattersconsulting.com/', site: "Mindset Matters Consulting", pass: 'Ujm>ET?hN12?M#Z#'},
    // { baseUrl: 'https://www.beachclubrealestate.com/', site: "Sea Pines Real Estate", pass: 'NzuWgVzSAJqyXFqR7Ndg1h9n4'},
    // { baseUrl: 'https://www.todayrealestate.com/', site: "Today Real Estate", pass: 'lfWcOuHOn5eawlPEFgsqjeMiu'},
    // { baseUrl: 'https://dgoody.com/', site: "Diane Goodwin"},
    // { baseUrl: 'https://karenmorganrealestate.com/', site: "Karen Morgan Real Estate", pass: 'NwP9GGQxT6E9N*3SNw6^^!q6h$I2tbsNy'},
    // { baseUrl: 'https://askalli.co/', site: "Ask Alli", pass: 'sVfiY2GYtW7ale6IB785yWWc1'},
    // { baseUrl: 'https://marcoheredia.com/', site: "Marco Heredia", pass: 'b~G0ZSH1<oVL0}J('},
    // { baseUrl: 'https://www.devsrealestate.com/', site: "Devs Real Estate", pass: 'tCSfNUWkUtu8x0Cg5Xso'},
    // { baseUrl: 'https://jluxproperties.com/', site: "Jlux Properties"},
    // { baseUrl: 'https://www.chalkerrealty.com/', site: "Chalker Realty"},
    // { baseUrl: 'https://www.edenregento.com/', site: "Eden Regento"},
    // { baseUrl: 'https://tphgsellsdc.com/', site: "Thomson Premier Homes Group"},
    // { baseUrl: 'https://www.therealestateranch.com/', site: "The Real Estate Ranch"},
    // { baseUrl: 'https://chadericksongroup.com/', site: "Chad Erickson Group"},
    // { baseUrl: 'https://www.luxurious-estates.com/', site: "Luxurious Real Estates"},
    // { baseUrl: 'https://www.bestcalgaryhomes.com/', site: "Best Calgary Homes", pass: 'xjxC42lpen7eOwMTGYcRrE8nk'},
    // { baseUrl: 'https://www.nadineblakelyhomes.com/', site: "Nadine Blakely", pass: 'eIEg6cTdq71PQh1anRHyGimO1'},
    // { baseUrl: 'https://www.waldencoloradorealestate.com/', site: "North Park Premier Real Estate", pass: 'mDTglSFbvy7ug9EyEFGXPOpP9'},
    // { baseUrl: 'https://www.winecountrycolbert.com/', site: "Wine Country Colbert Group", pass: '4qfp5hAZHNR3WO4oYuz7clTCc'},
    // { baseUrl: 'https://www.bhhscolonialhomessanmiguel.com/', site: "Colonial Homes San Miguel", countryFormats: ['US', 'MX']},
    // { baseUrl: 'https://katiesellsct.com/', site: "Katie O'Neil", pass: 'ffzoYcUbyDw}f]oC'},
    // { baseUrl: 'https://www.rabiarealty.com/', site: "Rabia Alizai", pass: '83wp59SFRoyXVpBLY2MmMFPpO'},
]


// ✅ Comment/uncomment which tests you want to run
export const enabledTests = [
  // 'adminTests',
  // 'globalTests',
  'homepageTests',
  // 'agentsTests',
  // 'socialsTests',
  // 'testimonialsTests',
  // 'propertiesTests',
  // 'communitiesTests',
  // 'roadmapTests',
  // 'contactTests',
  // 'externalpageTests',
  // 'sitemappageTests',

];